spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true